version: "3.9"

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ../mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ../mysql/mysql_alldata:/var/lib/mysql
    networks:
      - canchu_network

  app:
    image: gahwa17/canchu-server:latest
    restart: always
    container_name: canchu_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - canchu_network
    depends_on:
      - mysql
      - redis
    # command: sh -c "while ! nc -z mysql 3306; do sleep 1; done && node server.js"

  redis:
    image: redis
    restart: always
    networks:
      - canchu_network

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certificate.crt:/etc/nginx/certificate.crt:ro
      - ./nginx/private.key:/etc/nginx/private.key:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - canchu_network
    depends_on:
      - app

volumes:
  mysql_data:

networks:
  canchu_network:
    driver: bridge
